Hidden Spy and health check on Entities
MrBuiza/LoginTest pull request #4
Opened 2023-09-13 11:55 UTC by MrBuiza

Spy to has an additional field called hidden which is a Boolean.
New methods created which calculate and return whether spy is hidden or not.
Implemented code which calculates how much health an entity has and then returns whether they are healthy: "healthy"(80-100 health) "unhealthy"(40-80) "need medic"(1-40)
Run main to test.

2023-09-14 09:24 UTC, KleoG approved these changes
LGTM

2023-09-15 14:04 UTC, KleoG requested changes

2023-09-15 14:04 UTC, KleoG commented on LoginTest/src/Task3/Task3Main.java
> +        System.out.println("These are the current accounts: " + mateoAcc.getName() + ", " + kleoAcc.getName());
Change this so that it displays all of the accounts inside of bank, instead of you manually having to write each account

2023-09-15 14:05 UTC, MrBuiza commented on LoginTest/src/Task3/Task3Main.java
> +        System.out.println("These are the current accounts: " + mateoAcc.getName() + ", " + kleoAcc.getName());
NO.

2023-09-15 16:20 UTC, merged

2023-09-15 16:21 UTC, MrBuiza reviewed
done